import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
// import { CartProvider } from "@/context/cartContext";
import { CartProvider } from "@/context/cartContext";
import { ProductProvider } from "@/context/ProductContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Online shoping - Amazon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <ProductProvider>
            <CartProvider>
              {children}
              <ToastContainer position="top-right" autoClose={3000} />
            </CartProvider>
          </ProductProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
